// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Ewda11CEBitrrdvSsCQAivJNKCpsxC4',
    appId: '1:467637414689:web:53d40e1d274d65d8e7ec60',
    messagingSenderId: '467637414689',
    projectId: 'infinite-deck-429307-i6',
    authDomain: 'infinite-deck-429307-i6.firebaseapp.com',
    storageBucket: 'infinite-deck-429307-i6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQyOtNH424SlWMTgxjqrKkIbHsGKikfIc',
    appId: '1:467637414689:android:f973eabbb777ac45e7ec60',
    messagingSenderId: '467637414689',
    projectId: 'infinite-deck-429307-i6',
    storageBucket: 'infinite-deck-429307-i6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQj7dsggscKIDOpcJarjWPhecTv3Ol6z4',
    appId: '1:467637414689:ios:e791e7f48fef9140e7ec60',
    messagingSenderId: '467637414689',
    projectId: 'infinite-deck-429307-i6',
    storageBucket: 'infinite-deck-429307-i6.firebasestorage.app',
    iosBundleId: 'com.example.picturoApp',
  );
}
