// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6LsAihWTucNM5g0KC2kdPh_ygbLL5xI',
    appId: '1:414535387061:android:af0a6e651b6a5c4b0b3bfc',
    messagingSenderId: '414535387061',
    projectId: 'picturoenglish-1012d',
    storageBucket: 'picturoenglish-1012d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRBl8DbQHLoMzkLVJmSsrfIrO98cHu6Y',
    appId: '1:414535387061:ios:d6583d66f993bef00b3bfc',
    messagingSenderId: '414535387061',
    projectId: 'picturoenglish-1012d',
    storageBucket: 'picturoenglish-1012d.firebasestorage.app',
    iosBundleId: 'com.example.picturoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvIKre09LheDb4dJFN559bvxii-ZKpcQ',
    appId: '1:414535387061:web:c78374794c6100020b3bfc',
    messagingSenderId: '414535387061',
    projectId: 'picturoenglish-1012d',
    authDomain: 'picturoenglish-1012d.firebaseapp.com',
    storageBucket: 'picturoenglish-1012d.firebasestorage.app',
    measurementId: 'G-WLC056H15S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRBl8DbQHLoMzkLVJmSsrfIrO98cHu6Y',
    appId: '1:414535387061:ios:d6583d66f993bef00b3bfc',
    messagingSenderId: '414535387061',
    projectId: 'picturoenglish-1012d',
    storageBucket: 'picturoenglish-1012d.firebasestorage.app',
    iosBundleId: 'com.example.picturoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrvIKre09LheDb4dJFN559bvxii-ZKpcQ',
    appId: '1:414535387061:web:ff7c2ec835c8cb440b3bfc',
    messagingSenderId: '414535387061',
    projectId: 'picturoenglish-1012d',
    authDomain: 'picturoenglish-1012d.firebaseapp.com',
    storageBucket: 'picturoenglish-1012d.firebasestorage.app',
    measurementId: 'G-KJQQ1BJ6NS',
  );

}